baseURL = 'smedje.xyz'
languageCode = 'en-us'
title = 'smedje'
theme = 'risotto'

# For hugo >= 0.60.0, enable inline HTML
#[markup.goldmark.renderer]
#unsafe = true

# Automatically add content sections to main menu
#sectionPagesMenu = "main"

copyright = "© MIT license"

[[menu.main]]
name = "Hobbies"
url = "/hobbies"
weight = 20

[[menu.main]]
name = "Forge"
url = "/forge"
weight = 30

[[menu.main]]
name = "Website"
url = "/website"
weight = 40

[params]
noindex = true

[params.theme]
#palette = "base16-dark"
palette = "dracula"

[params.about]
title = "smedje"
description = "IT enthusiast, loves to study subjects that don't have much to do with each other"
logo = "images/profile.png"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "email"
url = "mailto:smedje@smedje.xyz"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/suyaseongi"

[[params.socialLinks]]
icon = "fa-solid fa-skull"
title = "Root Me"
url = "https://www.root-me.org/smedje-sh"

[markup]
  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true