baseURL = '/'
languageCode = 'en-us'
title = 'smedje'
theme = 'risotto'

# Automatically add content sections to main menu
#sectionPagesMenu = "main"

[[menu.main]]
name = "home"
url = "/posts"

[params]
noindex = false

[params.theme]
#palette = "base16-dark"
palette = "dracula"

[params.about]
title = "smedje"
description = "IT enthusiast, loves to study subjects that don't have much to do with each other"
logo = "images/profile.png"

[markup]
  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true